version: "2"

services:
  app:
    build:
      context: .
    image: ubuntu:latest
    volumes:
    - ./privatevibez:/privatevibez
    - /app/db # Mounting /mnt/Python to /app/db
    command: >
      sh -c "
        apt-get update &&
        apt upgrade -y &&
        apt install software-properties-common -y &&
        apt-add-repository multiverse &&
        apt-get update &&
        apt-get install unrar -y &&
        apt-get install ffmpeg -y &&
        apt-get install -y python3 python3-pip &&
        python /mnt/Python/MediaFlow.py && 
        python manage.py clearsessions &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      " 

    ports:
    - 8000:8000
    environment:
    - SECRET_KEY=devsecretkey
    - DEBUG=1




  # db:
  #   image: postgres:13.0-alpine
  #   environment:
  #   - POSTGRES_DB=privatevibezdb
  #   - POSTGRES_USER=devuser
  #   - POSTGRES_PASSWORD=password
