version: "2"

services:
  app:
    build:
      context: .
    image: ubuntu:latest
    volumes:
    - ./privatevibez:/privatevibez
    command: >
      sh -c "

        python manage.py runserver 0.0.0.0:8000
      " 

    ports:
    - 8000:8000
    environment:
    - SECRET_KEY=devsecretkey
    - DEBUG=1




  # db:
  #   image: postgres:13.0-alpine
  #   environment:
  #   - POSTGRES_DB=privatevibezdb
  #   - POSTGRES_USER=devuser
  #   - POSTGRES_PASSWORD=password
