version: "3.9"

services:
  app:
    build:
      context: .

    command: >
      sh -c "python manage.py clearsessions && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
    - ./privatevibez:/privatevibez
    - ./privatevibez:/app/db 
    ports:
    - 8000:8000
    environment:
    - SECRET_KEY=devsecretkey
    - DEBUG=1




  # db:
  #   image: postgres:13.0-alpine
  #   environment:
  #   - POSTGRES_DB=privatevibezdb
  #   - POSTGRES_USER=devuser
  #   - POSTGRES_PASSWORD=password
