# Generated by Django 3.0.5 on 2023-07-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Is_Sent_Invite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
