# Generated by Django 3.0.5 on 2022-12-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_status',
            old_name='User_status',
            new_name='Id_file',
        ),
    ]
