# Generated by Django 4.2.5 on 2023-10-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_item_availed_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Availed',
            field=models.ManyToManyField(blank=True, null=True, related_name='Item_Avail', to='accounts.item_availed'),
        ),
    ]
