# Generated by Django 3.0.5 on 2023-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230802_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Decline_Message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
