# Generated by Django 3.1.5 on 2023-08-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230805_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Ip_Address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
