# Generated by Django 3.0.5 on 2022-12-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221229_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Birth_dat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='Id_file',
            field=models.ImageField(blank=True, null=True, upload_to='ID'),
        ),
    ]
