# Generated by Django 3.0.5 on 2023-01-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221230_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Vibez',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
