# Generated by Django 3.1.5 on 2023-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Ip_Address_Expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
