# Generated by Django 3.0.5 on 2023-01-06 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_user_data_vibez'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_Acters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=500, null=True)),
                ('Staff', models.CharField(blank=True, max_length=500, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Reported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL)),
                ('Reporty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='Birth_dat',
            new_name='Birth_Date',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='Id_file',
            new_name='Id_File',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='timestamp',
            new_name='Timestamp',
        ),
        migrations.RenameField(
            model_name='user_status',
            old_name='User_status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='user_status',
            old_name='timestamp',
            new_name='Timestamp',
        ),
        migrations.AddField(
            model_name='user_data',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Body_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='I_Am',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Interested_In',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='Real_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
