# Generated by Django 3.1.5 on 2023-08-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_ip_address_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
