# Generated by Django 3.0.5 on 2023-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230106_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='Vibez',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
