# Generated by Django 3.1.5 on 2023-08-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0035_room_data_room_rules'),
        ('accounts', '0011_auto_20230811_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_availed',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Broadcaster', to='rooms.room_data'),
        ),
    ]
