# Generated by Django 3.0.5 on 2023-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_memos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='U_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
