# Generated by Django 3.1.5 on 2023-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_item_availed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_availed',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
