# Generated by Django 3.1.5 on 2023-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230901_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='Free_spins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
