# Generated by Django 3.1.5 on 2023-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_data_free_spins'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Badge',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_badge'),
        ),
    ]
