# Generated by Django 3.0.5 on 2023-01-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
