# Generated by Django 4.2.5 on 2023-09-25 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_alter_country_neighbours'),
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.region')),
            ],
        ),
        migrations.CreateModel(
            name='Blocked_Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.CITIES_COUNTRY_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room_data',
            name='Blocked_Countries',
            field=models.ManyToManyField(blank=True, related_name='block_countries', to='rooms.blocked_countries'),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Blocked_Regions',
            field=models.ManyToManyField(blank=True, related_name='block_regions', to='rooms.blocked_regions'),
        ),
    ]
