# Generated by Django 3.0.5 on 2023-01-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20230102_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
