# Generated by Django 4.2.5 on 2023-09-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_blocked_regions_blocked_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room_data',
            name='Viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to='rooms.room_viewer'),
        ),
    ]
