# Generated by Django 3.0.5 on 2023-01-03 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_room_data_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Real_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('I_Am', models.CharField(blank=True, max_length=200, null=True)),
                ('Interested_In', models.CharField(blank=True, max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Language', models.CharField(blank=True, max_length=200, null=True)),
                ('Body_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Profile_Pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
