# Generated by Django 4.2.6 on 2023-10-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_social_media_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Broadcaster_Lovense_Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Button_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Vibez_Cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
