# Generated by Django 4.2.6 on 2023-10-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_test_broadcaster_lovense_toy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Feature_MMM_button',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='Feature_OHYes_button',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='Feature_OH_button',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
