# Generated by Django 3.0.5 on 2023-01-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_menu_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_data',
            old_name='Body_Type',
            new_name='Menu_Name',
        ),
        migrations.RenameField(
            model_name='menu_data',
            old_name='I_Am',
            new_name='Menu_Time',
        ),
        migrations.RenameField(
            model_name='menu_data',
            old_name='Age',
            new_name='Vibez_Cost',
        ),
        migrations.RemoveField(
            model_name='menu_data',
            name='Interested_In',
        ),
        migrations.RemoveField(
            model_name='menu_data',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='menu_data',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='menu_data',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='menu_data',
            name='Real_Name',
        ),
    ]
