# Generated by Django 4.2.6 on 2023-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_data_feature_mmm_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Feature_MMM_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='Feature_OHYes_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='Feature_OH_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
