# Generated by Django 3.0.5 on 2023-01-03 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_dice_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Follow',
            field=models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
