# Generated by Django 4.2.6 on 2023-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_data_feature_mmm_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Strength_MMM_button',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='Strength_OHYes_button',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='Strength_OH_button',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
