# Generated by Django 3.0.5 on 2023-01-03 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0007_room_data_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Thumb',
            field=models.ManyToManyField(blank=True, related_name='thumb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Thumb_down',
            field=models.ManyToManyField(blank=True, related_name='thumb_down', to=settings.AUTH_USER_MODEL),
        ),
    ]
