# Generated by Django 4.2.6 on 2023-10-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_data_strength_mmm_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Promotion_Invitation_Code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
