# Generated by Django 3.0.5 on 2023-01-03 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0009_bad_acters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bad_acters',
            old_name='User',
            new_name='reporty',
        ),
        migrations.RemoveField(
            model_name='bad_acters',
            name='room',
        ),
        migrations.AddField(
            model_name='bad_acters',
            name='reported',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
