# Generated by Django 3.0.5 on 2023-01-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_bad_acters_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bad_acters',
            name='User',
        ),
    ]
