# Generated by Django 3.0.5 on 2023-01-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_remove_bad_acters_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad_acters',
            name='User',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
