# Generated by Django 3.0.5 on 2023-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20230106_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Tab',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
