# Generated by Django 3.0.5 on 2023-01-09 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0015_room_data_tab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following',
            new_name='Follows',
        ),
    ]
