# Generated by Django 3.0.5 on 2023-01-09 23:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0017_auto_20230109_2317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumb',
            new_name='Thumbs',
        ),
    ]
