# Generated by Django 3.0.5 on 2023-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_auto_20230109_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Private_Chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Private_Chat_Price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Public_Chat',
            field=models.BooleanField(default=True),
        ),
    ]
