# Generated by Django 3.0.5 on 2023-01-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_auto_20230110_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
