# Generated by Django 3.0.5 on 2023-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0020_room_data_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_sesson',
            name='Goal_currrent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
