# Generated by Django 3.0.5 on 2023-01-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_room_sesson_goal_currrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_sesson',
            old_name='Goal_currrent',
            new_name='Goal_Currrent',
        ),
    ]
