# Generated by Django 3.0.5 on 2023-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_auto_20230110_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Duration_MMM_button',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Duration_OHYes_button',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Duration_OH_button',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Price_MMM_button',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Price_OHYes_button',
            field=models.IntegerField(blank=True, default=75, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Price_OH_button',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Strength_MMM_button',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Strength_OHYes_button',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Strength_OH_button',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
