# Generated by Django 3.0.5 on 2023-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_auto_20230110_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Is_Active',
            field=models.BooleanField(default=False),
        ),
    ]
