# Generated by Django 3.0.5 on 2023-07-27 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0024_room_data_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_cost_per_spin', models.IntegerField(blank=True, null=True)),
                ('Win_3_of_a_kind_prize', models.CharField(blank=True, max_length=200, null=True)),
                ('Win_2_of_a_kind_prize', models.CharField(blank=True, max_length=200, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
