# Generated by Django 3.0.5 on 2023-07-27 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0025_slot_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Machine_limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_Three_of_a_kind_winners', models.IntegerField(blank=True, null=True)),
                ('Number_of_Two_of_a_kind_winners', models.IntegerField(blank=True, null=True)),
                ('Number_of_Three_of_a_kind_losers', models.IntegerField(blank=True, null=True)),
                ('Number_of_Two_of_a_kind_losers', models.IntegerField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='slot_machine',
            name='Prize',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slot_machine',
            name='Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slot_machine',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
