# Generated by Django 3.0.5 on 2023-07-28 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0027_auto_20230728_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='invitees',
            field=models.ManyToManyField(blank=True, null=True, through='rooms.Room_Data', to=settings.AUTH_USER_MODEL),
        ),
    ]
