# Generated by Django 3.0.5 on 2023-07-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_auto_20230728_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Private_Chat',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
    ]
