# Generated by Django 3.0.5 on 2023-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_auto_20230729_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Duration_OHYes_button',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
