# Generated by Django 3.0.5 on 2023-08-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_auto_20230729_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_Ip_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='room_data',
            name='Blocked_IP',
            field=models.ManyToManyField(blank=True, to='rooms.Block_Ip_Address'),
        ),
    ]
