# Generated by Django 3.0.5 on 2023-08-04 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0030_auto_20230804_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_data',
            name='Blocked_IP',
        ),
        migrations.CreateModel(
            name='Room_Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room_data',
            name='Visitors',
            field=models.ManyToManyField(blank=True, null=True, to='rooms.Room_Visitors'),
        ),
    ]
