# Generated by Django 3.1.5 on 2023-08-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('rooms', '0032_auto_20230805_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
            ],
        ),
        migrations.AddField(
            model_name='room_data',
            name='Blocked_Places',
            field=models.ManyToManyField(blank=True, related_name='blockings', to='rooms.Blocking'),
        ),
    ]
