# Generated by Django 3.1.5 on 2023-08-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('rooms', '0033_auto_20230807_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocked_Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='Blocked_Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
            ],
        ),
        migrations.RemoveField(
            model_name='room_data',
            name='Blocked_Places',
        ),
        migrations.DeleteModel(
            name='Blocking',
        ),
        migrations.AddField(
            model_name='room_data',
            name='Blocked_Countries',
            field=models.ManyToManyField(blank=True, related_name='block_countries', to='rooms.Blocked_Countries'),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Blocked_Regions',
            field=models.ManyToManyField(blank=True, related_name='block_regions', to='rooms.Blocked_Regions'),
        ),
    ]
