# Generated by Django 3.1.5 on 2023-08-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0034_auto_20230807_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Room_Rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
