# Generated by Django 3.1.5 on 2023-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0035_room_data_room_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='hashtags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
