# Generated by Django 3.1.5 on 2023-08-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0036_room_data_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
