# Generated by Django 3.1.5 on 2023-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0037_room_data_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Total_Viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
