# Generated by Django 3.1.5 on 2023-08-19 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0038_room_data_total_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='Broacaster',
        ),
        migrations.RemoveField(
            model_name='thumbs',
            name='Broacaster',
        ),
        migrations.AddField(
            model_name='follows',
            name='Broadcaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Broadcaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thumbs',
            name='Broadcaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thumb_Broadcaster', to=settings.AUTH_USER_MODEL),
        ),
    ]
