# Generated by Django 3.1.5 on 2023-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0039_auto_20230819_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Room_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
