# Generated by Django 3.1.5 on 2023-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0040_room_data_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_machine',
            name='pot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
