# Generated by Django 3.1.5 on 2023-08-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0041_slot_machine_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_machine',
            name='pot_increase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
