# Generated by Django 3.1.5 on 2023-08-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0042_slot_machine_pot_increase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Machine_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_Machine_Spin_Cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
