# Generated by Django 3.1.5 on 2023-09-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_promotion'),
        ('rooms', '0043_slot_machine_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Room_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.promotion'),
        ),
    ]
