# Generated by Django 3.1.5 on 2023-09-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0044_room_data_room_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_machine_data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
