# Generated by Django 3.1.5 on 2023-09-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20230909_1042'),
        ('rooms', '0045_slot_machine_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Room_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_promotion', to='staff.promotion'),
        ),
    ]
