# Generated by Django 3.1.5 on 2023-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0047_lottery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_Machine_Spin_Cost', models.IntegerField(blank=True, null=True)),
                ('Lottery_Spin_Cost', models.IntegerField(blank=True, null=True)),
                ('Dice_Spin_Cost', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Slot_Machine_Data',
        ),
    ]
