# Generated by Django 3.1.5 on 2023-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0048_auto_20230920_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_data',
            name='Is_Dice_Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Is_Lottery_Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room_data',
            name='Is_Menu_Active',
            field=models.BooleanField(default=False),
        ),
    ]
