# Generated by Django 3.1.5 on 2023-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0050_dice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot_machine',
            name='pot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
