# Generated by Django 3.1.5 on 2023-09-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0051_auto_20230923_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_data',
            name='Revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
