# Generated by Django 3.0.5 on 2023-01-23 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoProject_Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToDoProject_Dev_Staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDolist_Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(blank=True, max_length=200, null=True)),
                ('Done', models.BooleanField(default=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Coder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToDolist_Dev_Coder', to=settings.AUTH_USER_MODEL)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToDolist_Dev_Staff', to=settings.AUTH_USER_MODEL)),
                ('ToDoProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.ToDoProject_Dev')),
            ],
        ),
    ]
