# Generated by Django 4.2.6 on 2023-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatevibezrevenue',
            name='Test_Fav_Buttons_Revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
