# Generated by Django 3.0.5 on 2023-01-23 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_auto_20230123_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist_dev',
            name='Staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ToDolist_Dev_Staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoproject_dev',
            name='Staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ToDoProject_Dev_Staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
