# Generated by Django 4.2.6 on 2023-10-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_privatevibezrevenue_vibez_to_dollar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='Total_Viewers',
        ),
        migrations.CreateModel(
            name='Promotion_Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viewer', models.CharField(blank=True, max_length=250, null=True)),
                ('Promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_viewers', to='staff.promotion')),
            ],
        ),
    ]
