# Generated by Django 4.2.6 on 2023-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_promotion_total_viewers_promotion_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatevibezrevenue',
            name='Broadcaster_Earning_Per_Invite',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
