# Generated by Django 3.0.5 on 2023-07-19 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0005_auto_20230718_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRoomManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Name', to=settings.AUTH_USER_MODEL)),
                ('staff_list', models.ManyToManyField(blank=True, null=True, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
