# Generated by Django 3.0.5 on 2023-07-19 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0006_staffroommanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffroommanager',
            name='staff_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
