# Generated by Django 3.0.5 on 2023-07-20 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('staff', '0008_staffmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmanager',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
    ]
