# Generated by Django 3.0.5 on 2023-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20230720_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmanager',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
