# Generated by Django 3.0.5 on 2023-07-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20230722_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmanager',
            options={'permissions': [('can_add_staff', 'Can add staff'), ('can_edit_staff', 'Can edit a staff'), ('can_delete_staff', 'Can delete a staff')]},
        ),
    ]
