# Generated by Django 3.0.5 on 2023-07-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('staff', '0011_auto_20230722_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmanager',
            name='permission',
        ),
        migrations.AddField(
            model_name='staffmanager',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
