# Generated by Django 3.0.5 on 2023-07-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20230722_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmanager',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
