# Generated by Django 3.0.5 on 2023-07-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staffmanager_logout_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmanager',
            options={'permissions': [('can_add_staff', 'Can add staff'), ('can_edit_staff', 'Can edit a staff'), ('can_delete_staff', 'Can delete a staff'), ('can_view_staff', 'Can view a staff'), ('can_view_dashboard', 'Can view a dashboard'), ('can_view_id_check', 'Can view a ID Check'), ('can_view_bad_acters', 'Can view a bad acters'), ('can_view_todo_list', 'Can view a todo list'), ('can_view_inbox', 'Can view a inbox')]},
        ),
    ]
