# Generated by Django 3.0.5 on 2023-07-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20230723_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmanager',
            old_name='user_permissions',
            new_name='permissions',
        ),
    ]
