# Generated by Django 3.0.5 on 2023-07-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20230726_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmanager',
            old_name='permissions',
            new_name='user_permissions',
        ),
    ]
