# Generated by Django 3.0.5 on 2023-08-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_memos'),
    ]

    operations = [
        migrations.AddField(
            model_name='memos',
            name='Subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
