# Generated by Django 3.0.5 on 2023-08-03 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0018_memos_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decline_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Decline_Message_Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
