# Generated by Django 3.1.5 on 2023-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_decline_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatevibezRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot_Machine_Revenue', models.IntegerField(blank=True, null=True)),
                ('Slot_Machine_Spin_Cost', models.IntegerField(blank=True, null=True)),
                ('Total_Vibez', models.IntegerField(blank=True, null=True)),
                ('Total_Cash', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
