# Generated by Django 3.1.5 on 2023-08-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_auto_20230831_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatevibezrevenue',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
