# Generated by Django 3.1.5 on 2023-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_privatevibezrevenue_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatevibezrevenue',
            name='Vibe_Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
