# Generated by Django 3.1.5 on 2023-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20230902_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Total_Cash',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
