# Generated by Django 3.1.5 on 2023-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_auto_20230902_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promotion_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Promotion_Earning', models.FloatField(blank=True, null=True)),
                ('Promotion_Registration_Limit', models.IntegerField(blank=True, null=True)),
                ('Duration', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
