# Generated by Django 3.1.5 on 2023-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
