# Generated by Django 3.1.5 on 2023-09-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_promotion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='Total_Viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
