# Generated by Django 3.1.5 on 2023-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20230909_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatevibezrevenue',
            name='Dice_Revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatevibezrevenue',
            name='Lottery_Revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
