# Generated by Django 4.2.5 on 2023-09-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_alter_decline_message_id_alter_memos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Chargeback',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Dice_Revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Lottery_Revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Slot_Machine_Revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Total_Cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Total_Vibez',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='privatevibezrevenue',
            name='Vibe_Cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
