# Generated by Django 3.0.5 on 2023-07-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230718_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='private',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='private',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='public',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
