# Generated by Django 3.1.5 on 2023-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_private_chat_invitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_chat_invitee',
            name='Is_Accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
