# Generated by Django 3.1.5 on 2023-08-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_private_chat_invitee_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private_chat_invitee',
            old_name='broadcaster',
            new_name='Broadcaster',
        ),
        migrations.RemoveField(
            model_name='private_chat_invitee',
            name='Invitee',
        ),
        migrations.RemoveField(
            model_name='private_chat_invitee',
            name='Is_Accepted',
        ),
        migrations.RemoveField(
            model_name='private_chat_invitee',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='private_chat_invitee',
            name='is_deleted',
        ),
        migrations.CreateModel(
            name='InviteeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Accepted', models.BooleanField(default=False, null=True)),
                ('Invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee_relationships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='private_chat_invitee',
            name='Invitee_relationships',
            field=models.ManyToManyField(blank=True, to='chat.InviteeRelationship'),
        ),
    ]
